version: "3.1"

services:
  wordpress:
    image: wordpress
    restart: always
    depends_on:
      - db
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql

  cli:
    build: ./cli/.
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      WORDPRESS_LOCALE: ${WORDPRESS_LOCALE}
      WORDPRESS_WEBSITE_TITLE: "Bertls Blog"
      WORDPRESS_WEBSITE_URL: "http://localhost"
      WORDPRESS_WEBSITE_URL_WITHOUT_HTTP: "localhost"
      WORDPRESS_WEBSITE_POST_URL_STRUCTURE: "/%year%/%postname%/"
      WORDPRESS_ADMIN_USER: "admin_user"
      WORDPRESS_ADMIN_PASSWORD: "admin_password"
      WORDPRESS_ADMIN_EMAIL: "admin@bluelake.at"

volumes:
  wordpress:
  db:
